import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :acari_server, AcariServerWeb.Endpoint,
  http: [port: 4000],
  https: [
    port: 4443,
    keyfile: "priv/cert/selfsigned_key.pem",
    certfile: "priv/cert/selfsigned.pem",
    cipher_suite: :strong
    # versions: [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :acari_server, AcariServerWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/acari_server_web/views/.*(ex)$},
      ~r{lib/acari_server_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "$date $time [$level] $message\n", level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Configure your database
config :acari_server, AcariServer.Repo,
  hostname: "localhost",
  port: 5432

config :acari_server, AcariServer.RepoManager,
  rw: "localhost:5432",
  ro: "localhost:5432"

config :acari_server, AcariServer, allow_unconfigured: false

config :acari_server, AcariServer.Listener,
  port: 50019,
  keyfile: "priv/cert/selfsigned_key.pem",
  certfile: "priv/cert/selfsigned.pem"

config :acari_server, AcariServer.TCPListener, port: 50020

config :acari_server, :zabbix,
  zbx_ext_url: "https://localhost:12443",
  zbx_api_url: "https://Admin:zabbix@localhost:10443",
  zbx_api_url_2: "http://Admin:zabbix@localhost:12080",
  zbx_snd_host: "localhost",
  zbx_snd_host_2: "localhost",
  zbx_snd_port_2: 12051


config :acari_server, :openstreetmap,
  # provider_url: nil
  provider_url: "http://10.33.33.32:8080/styles/klokantech-basic/{z}/{x}/{y}.png"
