use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :acari_server, AcariServerWeb.Endpoint,
  https: [
    port: 50020,
    cipher_suite: :strong,
    keyfile: "/etc/ssl/acari/ssl.key",
    certfile: "/etc/ssl/acari/ssl.crt"
  ],
  # This is critical for ensuring web-sockets properly authorize.
  url: [host: "localhost", port: 50020],
  check_origin: false,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:acari_server, :vsn)

# Do not print debug messages in production
config :logger, level: :info

config :acari_server, AcariServer.Listener,
  port: 50019,
  keyfile: "priv/cert/selfsigned_key.pem",
  certfile: "priv/cert/selfsigned.pem"

#import_config "docker.secret.exs"
